// Types for $payloadApi are auto-generated by Nuxt from app/plugins/payload-api.ts
// (see .nuxt/types/plugins.d.ts). No manual augmentation required.
import type { $Fetch } from 'ofetch'

declare module '#app' {
    interface NuxtApp {
        $payloadApi: $Fetch
    }
}

declare module 'vue' {
    interface ComponentCustomProperties {
        $payloadApi: $Fetch
    }
}

export {}
